POST http://localhost:3003/contributors
content-type: application/json

{
    "firstName": "Anderson",
    "lastName": "Santos",
    "participation": 40
}

###
# @name login
POST http://localhost:3003/user/login
content-type: application/json

{
    "email": "samyr5@lbn.com",
    "password": "123456"
}

###
# @name getProfile
GET http://localhost:3003/user/profile
Authorization: {{login.response.body.access_token}}

###
GET http://localhost:3003/user/{{getProfile.response.body.id}}
Authorization: {{login.response.body.access_token}}

###

POST http://localhost:3003/recipe
content-type: application/json
Authorization: {{login.response.body.access_token}}

{
    "title": "Big Mac 3",
    "description": "Três hamburgueres, alface, queijo, molho especial, cebola, picles num pão com gergilim"
}

###
GET http://localhost:3003/recipe/972d51e5-ded5-4010-8d96-d2ff5e4bd15f
Authorization: {{login.response.body.access_token}}
